export const Types = {
    login: '[auth] login', 
    logout: '[auth] logout ', 

    seterror: '[ui] seterror ', 
    removeerror: '[ui] removeerror ', 

    startlogin: '[ui] startlogin ', 
    finishlogin: '[ui] finishlogin ', 
    //gastos cualquier cosa
    gastonuevo: '[gastos] nuevo gasto ', 
    gastoactive: '[gastos] active gasto ', 
    cargargasto: '[gastos] cargar gasto ',  
    buscargasto: '[gastos] buscar gasto ',
    guardargasto: '[gastos] guardar gasto ', 
    eliminargasto: '[gastos] eliminar gasto ', 
    borrartodoalfinalizarsesion: '[gastos] borrar todo al finalizar sesion ',  
    agregarnuevogasto: '[gastos] agregar gasto cuando se crea el mismo ', 
    sumagasto: '[gastos] sumar gasto ',
    //gastos industriales
    gastonuevoindustrial: '[gastosindustrial] nuevo gasto ', 
    gastoactiveindustrial: '[gastosindustrial] active gasto ', 
    cargargastoindustrial: '[gastosindustrial] cargar gasto ', 
    guardargastoindustrial: '[gastosindustrial] guardar gasto ', 
    eliminargastoindustrial: '[gastosindustrial] eliminar gasto ', 
    borrartodoalfinalizarsesionindustrial: '[gastosindustrial] borrar todo al finalizar sesion ', 
    agregarnuevogastoindustrial: '[gastosindustrial] agregar gasto cuando se crea el mismo ', 
    buscargastoindustrial: '[gastoindustrial] buscar gasto ',  
    //gastos transporte
    gastonuevotransporte: '[gastostransporte] nuevo gasto ', 
    gastoactivetransporte: '[gastostransporte] active gasto ', 
    cargargastotransporte: '[gastostransporte] cargar gasto ', 
    guardargastotransporte: '[gastostransporte] guardar gasto ', 
    eliminargastotransporte: '[gastostransporte] eliminar gasto ', 
    borrartodoalfinalizarsesiontransporte: '[gastostransporte] borrar todo al finalizar sesion ', 
    agregarnuevogastotransporte: '[gastostransporte] agregar gasto cuando se crea el mismo ', 
    buscargastotransporte: '[gastotransporte] buscar gasto ',  
    //gasto hogar
    gastonuevohogar: '[gastoshogar] nuevo gasto ', 
    gastoactivehogar: '[gastoshogar] active gasto ', 
    cargargastohogar: '[gastoshogar] cargar gasto ', 
    guardargastohogar: '[gastoshogar] guardar gasto ', 
    eliminargastohogar: '[gastoshogar] eliminar gasto ', 
    borrartodoalfinalizarsesionhogar: '[gastoshogar] borrar todo al finalizar sesion ', 
    agregarnuevogastohogar: '[gastoshogar] agregar gasto cuando se crea el mismo ', 
    buscargastohogar: '[gastohogar] buscar gasto ', 
    //gastos impuestos
    gastonuevoimpuestos: '[gastosimpuestos] nuevo gasto ', 
    gastoactiveimpuestos: '[gastosimpuestos] active gasto ', 
    cargargastoimpuestos: '[gastosimpuestos] cargar gasto ', 
    guardargastoimpuestos: '[gastosimpuestos] guardar gasto ', 
    eliminargastoimpuestos: '[gastosimpuestos] eliminar gasto ', 
    borrartodoalfinalizarsesionimpuestos: '[gastosimpuestos] borrar todo al finalizar sesion ', 
    agregarnuevogastoimpuestos: '[gastosimpuestos] agregar gasto cuando se crea el mismo ', 
    buscargastoimpuesto: '[gastoimpuesto] buscar gasto ', 
} 